# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapbiomas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 110, 461, 551))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Shapefile = QtWidgets.QGroupBox(self.widget)
        self.Shapefile.setObjectName("Shapefile")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Shapefile)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditShape = QtWidgets.QLineEdit(self.Shapefile)
        self.lineEditShape.setObjectName("lineEditShape")
        self.horizontalLayout_4.addWidget(self.lineEditShape)
        self.pushButtonShape = QtWidgets.QPushButton(self.Shapefile)
        self.pushButtonShape.setObjectName("pushButtonShape")
        self.horizontalLayout_4.addWidget(self.pushButtonShape)
        self.verticalLayout.addWidget(self.Shapefile)
        self.Saida = QtWidgets.QGroupBox(self.widget)
        self.Saida.setObjectName("Saida")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Saida)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditOutput = QtWidgets.QLineEdit(self.Saida)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.horizontalLayout_5.addWidget(self.lineEditOutput)
        self.pushButtonOutput = QtWidgets.QPushButton(self.Saida)
        self.pushButtonOutput.setObjectName("pushButtonOutput")
        self.horizontalLayout_5.addWidget(self.pushButtonOutput)
        self.verticalLayout.addWidget(self.Saida)
        self.Configuracoes = QtWidgets.QGroupBox(self.widget)
        self.Configuracoes.setObjectName("Configuracoes")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Configuracoes)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBoxYear = QtWidgets.QSpinBox(self.Configuracoes)
        self.spinBoxYear.setMinimum(1985)
        self.spinBoxYear.setMaximum(2024)
        self.spinBoxYear.setProperty("value", 2024)
        self.spinBoxYear.setObjectName("spinBoxYear")
        self.horizontalLayout_6.addWidget(self.spinBoxYear)
        self.comboBoxProduct = QtWidgets.QComboBox(self.Configuracoes)
        self.comboBoxProduct.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxProduct.setObjectName("comboBoxProduct")
        self.horizontalLayout_6.addWidget(self.comboBoxProduct)
        self.pushButtonDownload = QtWidgets.QPushButton(self.Configuracoes)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout_6.addWidget(self.pushButtonDownload)
        self.verticalLayout.addWidget(self.Configuracoes)
        self.progressBarDownload = QtWidgets.QProgressBar(self.widget)
        self.progressBarDownload.setProperty("value", 0)
        self.progressBarDownload.setObjectName("progressBarDownload")
        self.verticalLayout.addWidget(self.progressBarDownload)
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout.addWidget(self.plainTextEditLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Shapefile.setTitle(_translate("MainWindow", "Shapefile"))
        self.pushButtonShape.setText(_translate("MainWindow", "Selecionar"))
        self.Saida.setTitle(_translate("MainWindow", "Saída"))
        self.pushButtonOutput.setText(_translate("MainWindow", "Salvar"))
        self.Configuracoes.setTitle(_translate("MainWindow", "Configurações"))
        self.pushButtonDownload.setText(_translate("MainWindow", "Baixar"))
        self.plainTextEditLog.setPlaceholderText(_translate("MainWindow", "Logs do processo aparecerão aqui..."))
